name: Deploy MTProto Proxy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker
      run: |
        sudo apt update
        sudo apt install -y docker.io
    - name: Run MTProto Proxy
      run: |
        docker run -d --name mtproto_proxy \
          -p 443:443 \
          -e SECRET=0123456789abcdef0123456789abcdef \
          -e TAG=dd5b9e98e5b0c876dcebb3f5a47cf5ad \
          telegrammessenger/proxy
